version: "3.9"
services:
#------------------------------ oknalider134.ru
  oknalider134.ru:
    container_name: oknalider134.ru
    build: .
    image: oknalider134.ru
    restart: unless-stopped
    ports:
      - "3003:80"
    networks:
        web:
            ipv4_address: 192.168.7.6

#------------------------------ NETWORK
networks:
    web:
        name: web
        # use the bridge driver, but enable IPv6
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.7.0/24
                  gateway: 192.168.7.1
